### ISSUE TITLE
Black and Wite after minimize cnping on Windows10

### ISSUE THREAD

**Issue by BolverBlitz** [cnlohr/cnping#54] opened 2019-03-18 21:08 UTC
![grafik](https://user-images.githubusercontent.com/35345288/54563769-61877700-49ca-11e9-8516-42099efc863e.png)

**Comment by dreua** [comment] 2019-03-20 21:48
Hello BolverBlitz, thank you for reporting this issue!

I can easily reproduce it on Windows 10. It is triggered only after minimize or <kbd>Windows</kbd>+<kbd>D</kbd> (which is essentially "minimize all" so no surprise). Hiding the cnping window with other windows is no problem. 

Unfortunately I have no idea what causes this and currently no solid plan on how to debug this, but hopefully I or someone else will come up with something.

**Comment by dreua** [comment] 2019-03-20 22:25
I just tried the exe from https://github.com/cnlohr/cnping/commit/dab665d732902fa3d3fe697af5ae8d46045909f0 and https://github.com/cnlohr/cnping/commit/5c42452616a85c6877f5502a828dc82f61212a80 with the same results, I think this bug has been there for ever.

**Comment by dreua** [comment] 2019-03-21 22:37
I found out that the problem does not exist when cnping is compiled with OpenGL (the Visual Studio project file of Rawdraw does this as default so I was kind of lucky finding this). 

With OpenGL minimizing is not a problem anymore but the font looks worse, so I guess you have to "choose your pain".

Top: Standard cnping after minimizing.
Bottom: OpenGL cnping (minimizing makes no difference)
![defaultVSogl](https://user-images.githubusercontent.com/15114715/54789057-934e4700-4c31-11e9-8cc1-72796c96e679.PNG)

**Comment by dreua** [comment] 2019-04-01 11:32
1. The bug is also triggered by resizing the window to minimal (i.e. zero) height. 
2. Another possible fix is the RASTERIZER flag instead of CNFGOGL. Maybe that is even better? (Performance looks good to me.)
3. I pulled in changes from rawdraw and my pull request there. The font looks the same now with OpenGL.

**Comment by cnlohr** [comment] 2019-09-24 07:40
@dreua I am up for considering this, though I'd really like to understand why my use of the Windows API would lead to this.  It would be good to fix the upstream in rawdraw.  Not sure if you've noticed, but I've merged a lot of stuff, including the not-needing-admin thing.

**Comment by dreua** [comment] 2019-09-24 14:07
It's been some time since I looked into that - I believe I searched the net for a bit but didn't really find something about this bug. Is there some keyword or documentation link for the API you are using here?

**Comment by cnlohr** [comment] 2019-09-27 01:39
(Unrelated to topic)

@dreua the work you are doing is AMAZING.  I really regret not making more time to work on github stuff earlier this year. I am working on something I think you may appreciate.  Do you have some mechanism we can communicate over more directly?  Discord?  I'm cnlohr#4125

**Comment by cnlohr** [comment] 2019-09-27 04:36
Anyone else who's attacked this:  Do you also feel like you're eating crazy pills.  None of this makes sense why it's reverting to 1bpp.

**Closed** 2019-09-27 04:54 UTC

**Comment by dreua** [comment] 2019-09-27 09:46
@cnlohr I sent you a friend request on discord (david#7284). Do you use telegram by any chance (@dreuamainz)?

**Comment by cnlohr** [comment] 2019-09-27 10:23
I do not use Telegram.

**Comment by dreua** [comment] 2019-09-28 11:13
Here is the fix, in case someone else is interested: https://github.com/cnlohr/rawdraw/commit/250023c48b956daa63763394fbda36450f246a0d
